/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica15;

import java.text.DecimalFormat;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Practica15 extends javax.swing.JFrame {

    /**
     * 
     */
    
    DefaultTableModel modelo; 
    DefaultTableModel modelo2; 
    
    public Practica15() {
        initComponents();
        modelo2 = (DefaultTableModel)jTabTiempoLlegadas.getModel();
               int num = 5;
        for(int i=0;i<modelo2.getRowCount();i++){
            modelo2.setValueAt(num, i, 0);
            num+=5;
        }
        
        modelo2.setValueAt(0.25, 0, 1);
        modelo2.setValueAt(0.5, 1, 1);
        modelo2.setValueAt(0.25, 2, 1);
        
        modelo2.setValueAt(0.01, 0, 2);
        modelo2.setValueAt(0.26, 1, 2);
        modelo2.setValueAt(0.75, 2, 2);
        
        modelo2.setValueAt(0.25, 0, 3);
        modelo2.setValueAt(0.75, 1, 3);
        modelo2.setValueAt(1, 2, 3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabPrincipal = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabTiempoLlegadas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSpinCantidadSimulacion = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabCliEspera = new javax.swing.JLabel();
        jLabTiempEspera = new javax.swing.JLabel();
        jLabPromEspera = new javax.swing.JLabel();
        jLabTiempoOscio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Practica 15", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTabPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de cliente", "Numero aleatorio", "Individual", "Acumulado", "Entrada", "Salida", "Tiempo de espera", "Espero?", "Tiempo de ocio del servidor"
            }
        ));
        jScrollPane1.setViewportView(jTabPrincipal);

        jTabTiempoLlegadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tiempo entre llegadas", "Probabilidad", "Probabilidad acumulada", "Probabilidad acumulada"
            }
        ));
        jTabTiempoLlegadas.setToolTipText("");
        jScrollPane2.setViewportView(jTabTiempoLlegadas);

        jButton1.setText("Simular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSpinCantidadSimulacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinCantidadSimulacionStateChanged(evt);
            }
        });

        jLabel1.setText("Numero de clientes");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tiempo entre llegadas");

        jLabel3.setText("Clientes esperando = ");

        jLabel4.setText("Tiempo de espera = ");

        jLabel5.setText("Promedio de tiempo de espera = ");

        jLabel6.setText("Tiempo de oscio = ");

        jLabCliEspera.setBackground(new java.awt.Color(255, 0, 51));
        jLabCliEspera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabCliEspera.setOpaque(true);

        jLabTiempEspera.setBackground(new java.awt.Color(255, 0, 51));
        jLabTiempEspera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabTiempEspera.setOpaque(true);

        jLabPromEspera.setBackground(new java.awt.Color(255, 0, 51));
        jLabPromEspera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabPromEspera.setOpaque(true);

        jLabTiempoOscio.setBackground(new java.awt.Color(255, 0, 51));
        jLabTiempoOscio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabTiempoOscio.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(590, 590, 590)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinCantidadSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabCliEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabTiempoOscio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabPromEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addComponent(jLabTiempEspera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jSpinCantidadSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabCliEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabTiempEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabPromEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabTiempoOscio, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinCantidadSimulacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinCantidadSimulacionStateChanged
        // TODO add your handling code here:
        modelo = (DefaultTableModel)jTabPrincipal.getModel();
        modelo.setRowCount((int)jSpinCantidadSimulacion.getValue());

    }//GEN-LAST:event_jSpinCantidadSimulacionStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //numeros aleatorios 
       Random azar = new Random();
       //para los numeros aleatorios de 3 cifras 
       DecimalFormat df = new DecimalFormat("###,##0.00");
       //numero de cliente 
       modelo.setValueAt(1, 0, 0);
       //numero aleatorio 
       modelo.setValueAt(0, 0, 1);
       // numero de clientes y numeros aleatorios 
        for(int i=1;i<modelo.getRowCount();i++){
           modelo.setValueAt(i+1, i, 0);
           modelo.setValueAt(df.format(azar.nextDouble()), i, 1);    
        }
        // tiempo entrre llegadas individual 
        modelo.setValueAt(0, 0, 2);
         for(int i=1;i<modelo.getRowCount();i++){
         double val1 = Double.parseDouble(modelo.getValueAt(i, 1)+"");
         
         double acum1 = Double.parseDouble(modelo2.getValueAt(0, 2)+"");
         double acum11 = Double.parseDouble(modelo2.getValueAt(0, 3)+"");
         
         double acum2 = Double.parseDouble(modelo2.getValueAt(1, 2)+"");
         double acum22 = Double.parseDouble(modelo2.getValueAt(1, 3)+"");
         
         double acum3 = Double.parseDouble(modelo2.getValueAt(2, 2)+"");
         double acum33 = Double.parseDouble(modelo2.getValueAt(2, 3)+"");
         //seleccion de tiempo entre llegadas individual 
         if(val1>=acum1&&val1<=acum11){
             modelo.setValueAt(modelo2.getValueAt(0, 0), i,2);
         }
         else if(val1>=acum2&&val1<=acum22){
             modelo.setValueAt(modelo2.getValueAt(1, 0), i,2);
         }
         else if(val1>=acum3&&val1<=acum33){
             modelo.setValueAt(modelo2.getValueAt(2, 0), i,2);
         }
         else {
              modelo.setValueAt(0, i, 2);
         }
         }
         // tiempo entre llegadas acumulado 
         modelo.setValueAt(0, 0,3);
         int suma = 0;
         for(int i=1;i<modelo.getRowCount();i++){
         suma += Integer.parseInt(modelo.getValueAt(i,2)+"");
         modelo.setValueAt(suma, i, 3);
         }
         
         // Entrada
         modelo.setValueAt(0, 0, 4);
        //salida 
        modelo.setValueAt(8,0,5);
        
        //Entrada y salida 
         for(int i=1;i<modelo.getRowCount();i++){
             int salidapasada = Integer.parseInt(modelo.getValueAt(i-1, 5)+"");
             int acumulado = Integer.parseInt(modelo.getValueAt(i, 3)+"");
             if(salidapasada>acumulado){
                modelo.setValueAt(salidapasada, i, 4);
             }else if(salidapasada<acumulado){
                 modelo.setValueAt(acumulado, i, 4);
             }
             int sal = Integer.parseInt(modelo.getValueAt(i, 4)+"")+8;
             modelo.setValueAt(sal, i, 5);
         }
       
         //tiempo de espera 
          for(int i=0;i<modelo.getRowCount();i++){
              int val = Integer.parseInt(modelo.getValueAt(i, 4)+"")- Integer.parseInt(modelo.getValueAt(i, 3)+"");
              modelo.setValueAt(val, i, 6);
          }
          //espero?
           for(int i=0;i<modelo.getRowCount();i++){
               int val = Integer.parseInt(modelo.getValueAt(i, 6)+"");
               if(val>0){
               modelo.setValueAt("Si",i, 7);
               }else {
               modelo.setValueAt("No",i, 7);
               }
           }
           
           //tiempo de ocio
           modelo.setValueAt(0, 0, 8);
         for(int i=1;i<modelo.getRowCount();i++){
             int salidapasada = Integer.parseInt(modelo.getValueAt(i-1, 5)+"");
             int entrada = Integer.parseInt(modelo.getValueAt(i, 4)+"");
             
             int tim = entrada - salidapasada;
             
             modelo.setValueAt(tim, i, 8);
         }
         
         //clientes esperando 
         int reng = (int)jSpinCantidadSimulacion.getValue()-1;
         int cliEspera = Integer.parseInt(modelo.getValueAt(reng, 5)+"") - Integer.parseInt(modelo.getValueAt(reng, 4)+"");
         jLabCliEspera.setText(cliEspera+"");
         
         //tiempo de espera y tiemo de oscio
         double sumaTiempoEspera = 0;
         double sumaTiempoOscio = 0;
         for(int i=0;i<modelo.getRowCount();i++){
         double val = Integer.parseInt(modelo.getValueAt(i, 6)+"");
         double valO = Integer.parseInt(modelo.getValueAt(i, 8)+"");
         sumaTiempoEspera+=val; 
         sumaTiempoOscio+=valO; 
         }
         //tiempo de espera 
         jLabTiempEspera.setText(sumaTiempoEspera+"");
         //tiempo de oscio
         jLabTiempoOscio.setText(sumaTiempoOscio+"");
         
         
         // tiempo de espera promedio
         double prom = sumaTiempoEspera/reng;
         jLabPromEspera.setText(df.format(prom));

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabCliEspera;
    private javax.swing.JLabel jLabPromEspera;
    private javax.swing.JLabel jLabTiempEspera;
    private javax.swing.JLabel jLabTiempoOscio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinCantidadSimulacion;
    private javax.swing.JTable jTabPrincipal;
    private javax.swing.JTable jTabTiempoLlegadas;
    // End of variables declaration//GEN-END:variables
}
